Import NumPy module
Run the following code cell to import the NumPy module:

In [1]:
import numpy as np

Populate arrays with specific numbers
Call np.array to create a NumPy matrix with your own hand-picked values. For example, the following call to np.array creates an 8-element vector:

In [2]:
one_dimensional_array = np.array([1.2, 1.1, 2.3, 3.4, 4.5, 5.6, 3.1, 8.4, 9.5]);
print(one_dimensional_array)

[1.2 1.1 2.3 3.4 4.5 5.6 3.1 8.4 9.5]


Populate arrays with sequences of numbers
You can populate an array with a sequence of numbers:

In [3]:
sequence_of_integers = np.arange(1,9);
print(sequence_of_integers);

[1 2 3 4 5 6 7 8]


Populate arrays with random numbers
NumPy provides various functions to populate matrices with random numbers across certain ranges. For example, np.random.randint generates random integers between a low and high value. The following call populates a 6-element vector with random integers between 50 and 100.

In [4]:
random_int_btw50_100 = np.random.randint(low = 50, high = 101, size = (6))
print(random_int_btw50_100)

[56 89 59 57 97 64]
